services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      ENV: production
      PORT: "8080"
      DATABASE_URL: postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-mydb}?sslmode=disable
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/?authSource=admin
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    external: true
    name: app_network
