/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * DatePlan API
 * デートプランを生成・管理するAPI
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface DtoCreatePlanRequest {
  /** 予算 (default=Noneを表現するためポインタを使用) */
  budget?: number;
  /** いついくか */
  date?: string;
  /** 行きたい場所 */
  desired_places?: string[];
  /** 終わりの時間 (default=Noneを表現するためポインタを使用) */
  end_time?: number;
  /** 車あり */
  has_car?: boolean;
  /** 場所(リスト),地名 */
  locations?: string[];
  /** 都道府県 (選ばせる項目) */
  prefecture: string;
  /** 関係性 */
  relationship?: string;
  /** 始まりの時間 */
  start_time?: number;
  /** テーマ */
  theme?: string;
  /** 時間帯 (朝、昼、夜) */
  time_slot?: string;
}

export interface DtoCreateUserRequest {
  email: string;
  name: string;
  password: string;
}

export interface DtoMovementInfo {
  /** 時間(分) */
  duration?: number;
  from?: string;
  /** 徒歩 / 電車 / 車 */
  method?: string;
  /** いつ表示するか */
  order?: number;
  to?: string;
}

export interface DtoOpeningHours {
  end?: number;
  start?: number;
}

export interface DtoSpotInfo {
  /** カフェ / 公園 / 映画館 */
  category?: string;
  /** 混雑度 */
  congestion?: number;
  description?: string;
  /** 屋内 / 屋外 */
  indoor_outdoor?: string;
  /** 緯度 */
  lat?: number;
  /** 経度 */
  lng?: number;
  name?: string;
  opening_hours?: DtoOpeningHours;
  /** いつ表示するか */
  order?: number;
  /** list[url] */
  photos?: string[];
  /** 価格帯 */
  price_range?: number;
  rating?: number;
  /** 滞在時間目安(分) */
  stay_time?: number;
}

export interface DtoWeatherInfo {
  /** 季節 */
  season?: string;
  /** 晴れ / 雨 / 曇り */
  status?: string;
  /** 気温 */
  temperature?: number;
}

export interface DtoPlanResponse {
  description?: string;
  movements?: DtoMovementInfo[];
  spots?: DtoSpotInfo[];
  theme?: string;
  weather?: DtoWeatherInfo;
}

export interface DtoUserResponse {
  email?: string;
  id?: number;
  name?: string;
}

export type GetHealth200 = {[key: string]: string};

export type PostPlans400 = {[key: string]: string};

export type PostPlans500 = {[key: string]: string};

export type GetUsers500 = {[key: string]: string};

export type PostUsers400 = {[key: string]: string};

export type PostUsers500 = {[key: string]: string};

export type DeleteUsersId400 = {[key: string]: string};

export type DeleteUsersId500 = {[key: string]: string};

export type GetUsersId400 = {[key: string]: string};

export type GetUsersId404 = {[key: string]: string};

export type GetUsersId500 = {[key: string]: string};

export type PutUsersId400 = {[key: string]: string};

export type PutUsersId500 = {[key: string]: string};

/**
 * @summary ヘルスチェック
 */
export const getHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetHealth200>> => {
    return axios.get(
      `/health`,options
    );
  }

/**
 * @summary デートプランを生成する
 */
export const postPlans = (
    dtoCreatePlanRequest: DtoCreatePlanRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DtoPlanResponse>> => {
    return axios.post(
      `/plans`,
      dtoCreatePlanRequest,options
    );
  }

/**
 * @summary ユーザー一覧取得
 */
export const getUsers = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DtoUserResponse[]>> => {
    return axios.get(
      `/users`,options
    );
  }

/**
 * @summary ユーザー作成
 */
export const postUsers = (
    dtoCreateUserRequest: DtoCreateUserRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DtoUserResponse>> => {
    return axios.post(
      `/users`,
      dtoCreateUserRequest,options
    );
  }

/**
 * @summary ユーザー削除
 */
export const deleteUsersId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.delete(
      `/users/${id}`,options
    );
  }

/**
 * @summary ユーザー取得
 */
export const getUsersId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DtoUserResponse>> => {
    return axios.get(
      `/users/${id}`,options
    );
  }

/**
 * @summary ユーザー更新
 */
export const putUsersId = (
    id: number,
    dtoCreateUserRequest: DtoCreateUserRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DtoUserResponse>> => {
    return axios.put(
      `/users/${id}`,
      dtoCreateUserRequest,options
    );
  }

export type GetHealthResult = AxiosResponse<GetHealth200>
export type PostPlansResult = AxiosResponse<DtoPlanResponse>
export type GetUsersResult = AxiosResponse<DtoUserResponse[]>
export type PostUsersResult = AxiosResponse<DtoUserResponse>
export type DeleteUsersIdResult = AxiosResponse<void>
export type GetUsersIdResult = AxiosResponse<DtoUserResponse>
export type PutUsersIdResult = AxiosResponse<DtoUserResponse>
